import './globals.css'
import type { Metadata } from 'next'
import Provider from './api/auth/Provider'
import localFont from '@next/font/local';

const playwriteDeutschlandGrundschrift = localFont({
  src: "../public/fonts/playwrite-deutschland-grundschrift.ttf",
  display: 'swap',
  variable: '--font-playwrite-deutschland-grundschrift',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={playwriteDeutschlandGrundschrift.variable}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
